# Generated by Django 5.2.8 on 2025-11-30 22:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Properties'},
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the property'),
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, help_text='Location/Area name', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='rent',
            field=models.DecimalField(decimal_places=2, default=0.00, help_text='Monthly rent amount', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(default=1, help_text='Number of rooms'),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('pending', 'Pending Inspection'), ('maintenance', 'Under Maintenance')], default='vacant', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='property',
            name='utilities',
            field=models.CharField(blank=True, help_text='e.g., Water, Electricity, Wi-Fi', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.TextField(help_text='Full address of the property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(help_text='e.g., House 1, Apartment 5B', max_length=255),
        ),
    ]
